/**
 * Injects Vercel/platform env vars into Angular production environment before build.
 * Set API_URL in Vercel project settings → Environment Variables.
 */
const fs = require('fs');
const path = require('path');

const apiUrl = process.env.API_URL || 'https://raas-api.onrender.com/api';
const outPath = path.join(__dirname, '../src/environments/environment.prod.ts');

const content = `// Auto-generated by scripts/set-env.js — do not edit manually
export const environment = {
  production: true,
  apiUrl: '${apiUrl.replace(/'/g, "\\'")}'
};
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log('✓ environment.prod.ts → apiUrl:', apiUrl);
