// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RAAS.Infrastructure.Data;

#nullable disable

namespace RAAS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RaasDbContext))]
    [Migration("20260702042244_AddInvestorCrmScaffold")]
    partial class AddInvestorCrmScaffold
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RAAS.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Line2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3234),
                            Description = "Traditional Rajasthani achar",
                            DisplayOrder = 1,
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Pickles",
                            Slug = "pickles",
                            UpdatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3234)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3249),
                            Description = "Crispy handmade papads",
                            DisplayOrder = 2,
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Papad",
                            Slug = "papad",
                            UpdatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3250)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3259),
                            Description = "Authentic spice blends",
                            DisplayOrder = 3,
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Masalas",
                            Slug = "masalas",
                            UpdatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3259)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3268),
                            Description = "Tangy homemade chutneys",
                            DisplayOrder = 4,
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Chutneys",
                            Slug = "chutneys",
                            UpdatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3269)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            CreatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3277),
                            Description = "Curated gift packs",
                            DisplayOrder = 5,
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Combos",
                            Slug = "combos",
                            UpdatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3278)
                        });
                });

            modelBuilder.Entity("RAAS.Domain.Entities.ComplianceCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvestorAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LandDealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvestorAccountId");

                    b.HasIndex("LandDealId");

                    b.ToTable("ComplianceCases");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("MinOrderAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            Code = "WELCOME10",
                            CreatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3594),
                            Description = "10% off on first order",
                            DiscountPercent = 10m,
                            IsActive = true,
                            MaxDiscountAmount = 100m,
                            MinOrderAmount = 299m,
                            UpdatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3595),
                            UsageCount = 0,
                            UsageLimit = 1000,
                            ValidFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidUntil = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RAAS.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.InvestmentFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FlowDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FundSource")
                        .HasColumnType("integer");

                    b.Property<Guid>("InvestorAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LandDealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvestorAccountId");

                    b.HasIndex("LandDealId");

                    b.ToTable("InvestmentFlows");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.InvestorAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("KycCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PanNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("PricingTierCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("TotalCommittedCapital")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountCode")
                        .IsUnique();

                    b.ToTable("InvestorAccounts");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.InvestorPayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvestorAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LandDealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("PaidOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvestorAccountId");

                    b.HasIndex("LandDealId");

                    b.ToTable("InvestorPayouts");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.LandDeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AcquisitionCost")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal>("AreaInAcres")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DealCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("ExpectedRevenue")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime?>("RegisteredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RegistrationCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DealCode")
                        .IsUnique();

                    b.ToTable("LandDeals");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CouponCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeliveryCharge")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("GuestEmail")
                        .HasColumnType("text");

                    b.Property<bool>("IsGuestOrder")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSampleOrder")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShippingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShippingPhone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ShippingPincode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShippingState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.PricingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IncludesAdvancedTracking")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludesBasicCrm")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludesComplianceDashboard")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MonthlyPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PricingPlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555501"),
                            Code = "BASIC_CRM",
                            CreatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3527),
                            IncludesAdvancedTracking = false,
                            IncludesBasicCrm = true,
                            IncludesComplianceDashboard = false,
                            IsActive = true,
                            MonthlyPrice = 14999m,
                            Name = "Basic CRM",
                            UpdatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3528)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555502"),
                            Code = "ADVANCED_INVESTMENT",
                            CreatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3543),
                            IncludesAdvancedTracking = true,
                            IncludesBasicCrm = true,
                            IncludesComplianceDashboard = false,
                            IsActive = true,
                            MonthlyPrice = 29999m,
                            Name = "Advanced Investment Tracking",
                            UpdatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3544)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555503"),
                            Code = "COMPLIANCE_DASHBOARD",
                            CreatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3555),
                            IncludesAdvancedTracking = true,
                            IncludesBasicCrm = true,
                            IncludesComplianceDashboard = true,
                            IsActive = true,
                            MonthlyPrice = 44999m,
                            Name = "Compliance Dashboard Suite",
                            UpdatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3555)
                        });
                });

            modelBuilder.Entity("RAAS.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("GalleryUrls")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("HealthBenefits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBestseller")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSampleEligible")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpiceLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("Story")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsageSuggestions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111101"),
                            CompareAtPrice = 299m,
                            CreatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3462),
                            Description = "Sun-dried raw mangoes in mustard oil with traditional spices",
                            GalleryUrls = new[] { "https://images.unsplash.com/photo-1609501676725-7186f017a9fe?w=800" },
                            HealthBenefits = "Rich in probiotics, aids digestion, boosts immunity.",
                            ImageUrl = "https://images.unsplash.com/photo-1609501676725-7186f017a9fe?w=800",
                            Ingredients = "Raw mango, mustard oil, fenugreek, fennel, red chili, turmeric, salt",
                            IsActive = true,
                            IsBestseller = true,
                            IsSampleEligible = false,
                            Name = "Rajasthani Mango Pickle",
                            Price = 249m,
                            Rating = 4.5,
                            ReviewCount = 0,
                            Slug = "rajasthani-mango-pickle",
                            SpiceLevel = 2,
                            Stock = 150,
                            Story = "From the kitchens of Jodhpur, this pickle carries generations of family recipes.",
                            UpdatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3462),
                            UsageSuggestions = "Perfect with dal-rice, parathas, or Rajasthani thali.",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3486),
                            Description = "Crispy urad dal papad with black pepper and cumin",
                            GalleryUrls = new string[0],
                            HealthBenefits = "High protein, low fat snack. Cumin aids digestion.",
                            ImageUrl = "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800",
                            Ingredients = "Urad dal, black pepper, cumin, salt",
                            IsActive = true,
                            IsBestseller = true,
                            IsSampleEligible = false,
                            Name = "Masala Papad",
                            Price = 89m,
                            Rating = 4.5,
                            ReviewCount = 0,
                            Slug = "masala-papad",
                            SpiceLevel = 0,
                            Stock = 200,
                            Story = "Hand-rolled under the desert sun of Bikaner.",
                            UpdatedAt = new DateTime(2026, 7, 2, 4, 22, 43, 644, DateTimeKind.Utc).AddTicks(3486),
                            UsageSuggestions = "Roast over flame or microwave.",
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("RAAS.Domain.Entities.ProductView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductViews");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.Referral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRewarded")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReferredUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferrerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RewardAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("RewardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReferredUserId");

                    b.HasIndex("ReferrerId");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.StoreSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("StoreSettings");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GuestEmail")
                        .HasColumnType("text");

                    b.Property<bool>("HasClaimedSample")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsGuest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ReferralEarnings")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("ReferredByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ReferralCode")
                        .IsUnique();

                    b.HasIndex("ReferredByUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.Address", b =>
                {
                    b.HasOne("RAAS.Domain.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.ComplianceCase", b =>
                {
                    b.HasOne("RAAS.Domain.Entities.InvestorAccount", "InvestorAccount")
                        .WithMany("ComplianceCases")
                        .HasForeignKey("InvestorAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RAAS.Domain.Entities.LandDeal", "LandDeal")
                        .WithMany("ComplianceCases")
                        .HasForeignKey("LandDealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InvestorAccount");

                    b.Navigation("LandDeal");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.Event", b =>
                {
                    b.HasOne("RAAS.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("RAAS.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.InvestmentFlow", b =>
                {
                    b.HasOne("RAAS.Domain.Entities.InvestorAccount", "InvestorAccount")
                        .WithMany("InvestmentFlows")
                        .HasForeignKey("InvestorAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RAAS.Domain.Entities.LandDeal", "LandDeal")
                        .WithMany("InvestmentFlows")
                        .HasForeignKey("LandDealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestorAccount");

                    b.Navigation("LandDeal");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.InvestorPayout", b =>
                {
                    b.HasOne("RAAS.Domain.Entities.InvestorAccount", "InvestorAccount")
                        .WithMany("Payouts")
                        .HasForeignKey("InvestorAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RAAS.Domain.Entities.LandDeal", "LandDeal")
                        .WithMany("Payouts")
                        .HasForeignKey("LandDealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestorAccount");

                    b.Navigation("LandDeal");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.Order", b =>
                {
                    b.HasOne("RAAS.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("RAAS.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RAAS.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.Product", b =>
                {
                    b.HasOne("RAAS.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.ProductView", b =>
                {
                    b.HasOne("RAAS.Domain.Entities.Product", "Product")
                        .WithMany("ProductViews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RAAS.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.Referral", b =>
                {
                    b.HasOne("RAAS.Domain.Entities.User", "ReferredUser")
                        .WithMany()
                        .HasForeignKey("ReferredUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RAAS.Domain.Entities.User", "Referrer")
                        .WithMany("ReferralRecords")
                        .HasForeignKey("ReferrerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReferredUser");

                    b.Navigation("Referrer");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.User", b =>
                {
                    b.HasOne("RAAS.Domain.Entities.User", "ReferredBy")
                        .WithMany("Referrals")
                        .HasForeignKey("ReferredByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReferredBy");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.InvestorAccount", b =>
                {
                    b.Navigation("ComplianceCases");

                    b.Navigation("InvestmentFlows");

                    b.Navigation("Payouts");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.LandDeal", b =>
                {
                    b.Navigation("ComplianceCases");

                    b.Navigation("InvestmentFlows");

                    b.Navigation("Payouts");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductViews");
                });

            modelBuilder.Entity("RAAS.Domain.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("ReferralRecords");

                    b.Navigation("Referrals");
                });
#pragma warning restore 612, 618
        }
    }
}
